name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DO_SSH_KEY }}"

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          script: |
            cd /var/www/url-browser/
            git pull