name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode SSH key
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.DO_SSH_KEY }}" | base64 -d > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        script: |
          cd /root/apps/url-browser
          git pull